package com.springboot.sprintboottest.Repository;


import com.springboot.sprintboottest.Entity.roleSkill;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import javax.transaction.Transactional;

public interface RoleSkillRepository extends JpaRepository<roleSkill, Integer> {
    @Query(nativeQuery = true, value = "SELECT * FROM kesulu_online.role_skills" +
            " WHERE role_card_id = :role_card_id")
    roleSkill findRoleSkill(@Param("role_card_id") Integer role_card_id);

    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = "UPDATE kesulu_online.role_skills SET role_skill_accounting_growth = :role_skill_accounting_growth_v, role_skill_anthropology_growth = :role_skill_anthropology_growth_v, role_skill_evaluation_growth = :role_skill_evaluation_growth_v, role_skill_archaeology_growth = :role_skill_archaeology_growth_v, role_skill_writing_growth = :role_skill_writing_growth_v, role_skill_music_theory_growth = :role_skill_music_theory_growth_v, role_skill_morris_dance_growth = :role_skill_morris_dance_growth_v, role_skill_opera_singing_growth = :role_skill_opera_singing_growth_v, role_skill_whitewasher_painter_growth = :role_skill_whitewasher_painter_growth_v, role_skill_photography_growth = :role_skill_photography_growth_v, role_skill_dance_growth = :role_skill_dance_growth_v, role_skill_art_growth = :role_skill_art_growth_v, role_skill_forge_growth = :role_skill_forge_growth_v, role_skill_pottery_making_growth = :role_skill_pottery_making_growth_v, role_skill_technical_drawing_growth = :role_skill_technical_drawing_growth_v, role_skill_farming_growth = :role_skill_farming_growth_v, role_skill_typing_growth = :role_skill_typing_growth_v, role_skill_shorthand_growth = :role_skill_shorthand_growth_v, role_skill_blown_glass_tube_growth = :role_skill_blown_glass_tube_growth_v, role_skill_tailor_growth = :role_skill_tailor_growth_v, role_skill_make_wine_growth = :role_skill_make_wine_growth_v, role_skill_fishing_growth = :role_skill_fishing_growth_v, role_skill_sculpture_growth = :role_skill_sculpture_growth_v, role_skill_acrobatics_growth = :role_skill_acrobatics_growth_v, role_skill_seduce_growth = :role_skill_seduce_growth_v, role_skill_climb_growth = :role_skill_climb_growth_v, role_skill_computer_growth = :role_skill_computer_growth_v, role_skill_credit_growth = :role_skill_credit_growth_v, role_skill_cthulhu_mythos_growth = :role_skill_cthulhu_mythos_growth_v, role_skill_disguise_growth = :role_skill_disguise_growth_v, role_skill_dodge_growth = :role_skill_dodge_growth_v, role_skill_car_driving_growth = :role_skill_car_driving_growth_v, role_skill_electrical_maintenance_growth = :role_skill_electrical_maintenance_growth_v, role_skill_electronics_growth = :role_skill_electronics_growth_v, role_skill_speech_skill_growth = :role_skill_speech_skill_growth_v, role_skill_combat_fight_growth = :role_skill_combat_fight_growth_v, role_skill_combat_whip_growth = :role_skill_combat_whip_growth_v, role_skill_combat_electric_saw_growth = :role_skill_combat_electric_saw_growth_v, role_skill_combat_axe_growth = :role_skill_combat_axe_growth_v, role_skill_combat_sword_growth = :role_skill_combat_sword_growth_v, role_skill_combat_hinge_growth = :role_skill_combat_hinge_growth_v, role_skill_combat_flail_growth = :role_skill_combat_flail_growth_v, role_skill_combat_spear_growth = :role_skill_combat_spear_growth_v, role_skill_shoot_pistol_growth = :role_skill_shoot_pistol_growth_v, role_skill_shoot_rifle_shotgun_growth = :role_skill_shoot_rifle_shotgun_growth_v, role_skill_shoot_archery_growth = :role_skill_shoot_archery_growth_v, role_skill_shoot_flame_thrower_growth = :role_skill_shoot_flame_thrower_growth_v, role_skill_shoot_machine_gun_growth = :role_skill_shoot_machine_gun_growth_v, role_skill_shoot_heavy_weapon_growth = :role_skill_shoot_heavy_weapon_growth_v, role_skill_first_aid_growth = :role_skill_first_aid_growth_v, role_skill_history_growth = :role_skill_history_growth_v, role_skill_threaten_growth = :role_skill_threaten_growth_v, role_skill_jump_growth = :role_skill_jump_growth_v, role_skill_language_val1_growth = :role_skill_language_val1_growth_v, role_skill_language_val2_growth = :role_skill_language_val2_growth_v, role_skill_language_val3_growth = :role_skill_language_val3_growth_v, role_skill_mother_tongue_val_growth = :role_skill_mother_tongue_val_growth_v, role_skill_throw_growth = :role_skill_throw_growth_v, role_skill_track_growth = :role_skill_track_growth_v, role_skill_law_growth = :role_skill_law_growth_v, role_skill_library_use_growth = :role_skill_library_use_growth_v, role_skill_listen_growth = :role_skill_listen_growth_v, role_skill_locksmith_growth = :role_skill_locksmith_growth_v, role_skill_mechanical_repair_growth = :role_skill_mechanical_repair_growth_v, role_skill_medicine_growth = :role_skill_medicine_growth_v, role_skill_natural_world_growth = :role_skill_natural_world_growth_v, role_skill_navigate_growth = :role_skill_navigate_growth_v, role_skill_occult_growth = :role_skill_occult_growth_v, role_skill_operate_heavy_machinery_growth = :role_skill_operate_heavy_machinery_growth_v, role_skill_persuade_growth = :role_skill_persuade_growth_v, role_skill_drive_aircraft_growth = :role_skill_drive_aircraft_growth_v, role_skill_drive_ship_growth = :role_skill_drive_ship_growth_v, role_skill_psychoanalysis_growth = :role_skill_psychoanalysis_growth_v, role_skill_psychology_growth = :role_skill_psychology_growth_v, role_skill_ride_growth = :role_skill_ride_growth_v, role_skill_science_geology_growth = :role_skill_science_geology_growth_v, role_skill_science_chemistry_growth = :role_skill_science_chemistry_growth_v, role_skill_science_biology_growth = :role_skill_science_biology_growth_v, role_skill_science_math_growth = :role_skill_science_math_growth_v, role_skill_science_astronomy_growth = :role_skill_science_astronomy_growth_v, role_skill_science_physics_growth = :role_skill_science_physics_growth_v, role_skill_science_pharmacy_growth = :role_skill_science_pharmacy_growth_v, role_skill_science_botany_growth = :role_skill_science_botany_growth_v, role_skill_science_zoology_growth = :role_skill_science_zoology_growth_v, role_skill_science_cryptography_growth = :role_skill_science_cryptography_growth_v, role_skill_science_engineering_growth = :role_skill_science_engineering_growth_v, role_skill_science_meteorology_growth = :role_skill_science_meteorology_growth_v, role_skill_science_judicial_science_growth = :role_skill_science_judicial_science_growth_v, role_skill_sleight_of_hand_growth = :role_skill_sleight_of_hand_growth_v, role_skill_recon_growth = :role_skill_recon_growth_v, role_skill_stealth_growth = :role_skill_stealth_growth_v, role_skill_survival_growth = :role_skill_survival_growth_v, role_skill_swim_growth = :role_skill_swim_growth_v, role_skill_beast_training_growth = :role_skill_beast_training_growth_v, role_skill_diving_growth = :role_skill_diving_growth_v, role_skill_demolition_growth = :role_skill_demolition_growth_v, role_skill_read_lips_growth = :role_skill_read_lips_growth_v, role_skill_hypnosis_growth = :role_skill_hypnosis_growth_v, role_skill_artillery_growth = :role_skill_artillery_growth_v, role_skill_lore_val_growth = :role_skill_lore_val_growth_v WHERE role_card_id = :role_card_id_v")
    void updateRoleSkillGrowth(
            @Param("role_skill_accounting_growth_v") Integer role_skill_accounting_growth_v,
            @Param("role_skill_anthropology_growth_v") Integer role_skill_anthropology_growth_v,
            @Param("role_skill_evaluation_growth_v") Integer role_skill_evaluation_growth_v,
            @Param("role_skill_archaeology_growth_v") Integer role_skill_archaeology_growth_v,
            @Param("role_skill_writing_growth_v") Integer role_skill_writing_growth_v,
            @Param("role_skill_music_theory_growth_v") Integer role_skill_music_theory_growth_v,
            @Param("role_skill_morris_dance_growth_v") Integer role_skill_morris_dance_growth_v,
            @Param("role_skill_opera_singing_growth_v") Integer role_skill_opera_singing_growth_v,
            @Param("role_skill_whitewasher_painter_growth_v") Integer role_skill_whitewasher_painter_growth_v,
            @Param("role_skill_photography_growth_v") Integer role_skill_photography_growth_v,
            @Param("role_skill_dance_growth_v") Integer role_skill_dance_growth_v,
            @Param("role_skill_art_growth_v") Integer role_skill_art_growth_v,
            @Param("role_skill_forge_growth_v") Integer role_skill_forge_growth_v,
            @Param("role_skill_pottery_making_growth_v") Integer role_skill_pottery_making_growth_v,
            @Param("role_skill_technical_drawing_growth_v") Integer role_skill_technical_drawing_growth_v,
            @Param("role_skill_farming_growth_v") Integer role_skill_farming_growth_v,
            @Param("role_skill_typing_growth_v") Integer role_skill_typing_growth_v,
            @Param("role_skill_shorthand_growth_v") Integer role_skill_shorthand_growth_v,
            @Param("role_skill_blown_glass_tube_growth_v") Integer role_skill_blown_glass_tube_growth_v,
            @Param("role_skill_tailor_growth_v") Integer role_skill_tailor_growth_v,
            @Param("role_skill_make_wine_growth_v") Integer role_skill_make_wine_growth_v,
            @Param("role_skill_fishing_growth_v") Integer role_skill_fishing_growth_v,
            @Param("role_skill_sculpture_growth_v") Integer role_skill_sculpture_growth_v,
            @Param("role_skill_acrobatics_growth_v") Integer role_skill_acrobatics_growth_v,
            @Param("role_skill_seduce_growth_v") Integer role_skill_seduce_growth_v,
            @Param("role_skill_climb_growth_v") Integer role_skill_climb_growth_v,
            @Param("role_skill_computer_growth_v") Integer role_skill_computer_growth_v,
            @Param("role_skill_credit_growth_v") Integer role_skill_credit_growth_v,
            @Param("role_skill_cthulhu_mythos_growth_v") Integer role_skill_cthulhu_mythos_growth_v,
            @Param("role_skill_disguise_growth_v") Integer role_skill_disguise_growth_v,
            @Param("role_skill_dodge_growth_v") Integer role_skill_dodge_growth_v,
            @Param("role_skill_car_driving_growth_v") Integer role_skill_car_driving_growth_v,
            @Param("role_skill_electrical_maintenance_growth_v") Integer role_skill_electrical_maintenance_growth_v,
            @Param("role_skill_electronics_growth_v") Integer role_skill_electronics_growth_v,
            @Param("role_skill_speech_skill_growth_v") Integer role_skill_speech_skill_growth_v,
            @Param("role_skill_combat_fight_growth_v") Integer role_skill_combat_fight_growth_v,
            @Param("role_skill_combat_whip_growth_v") Integer role_skill_combat_whip_growth_v,
            @Param("role_skill_combat_electric_saw_growth_v") Integer role_skill_combat_electric_saw_growth_v,
            @Param("role_skill_combat_axe_growth_v") Integer role_skill_combat_axe_growth_v,
            @Param("role_skill_combat_sword_growth_v") Integer role_skill_combat_sword_growth_v,
            @Param("role_skill_combat_hinge_growth_v") Integer role_skill_combat_hinge_growth_v,
            @Param("role_skill_combat_flail_growth_v") Integer role_skill_combat_flail_growth_v,
            @Param("role_skill_combat_spear_growth_v") Integer role_skill_combat_spear_growth_v,
            @Param("role_skill_shoot_pistol_growth_v") Integer role_skill_shoot_pistol_growth_v,
            @Param("role_skill_shoot_rifle_shotgun_growth_v") Integer role_skill_shoot_rifle_shotgun_growth_v,
            @Param("role_skill_shoot_archery_growth_v") Integer role_skill_shoot_archery_growth_v,
            @Param("role_skill_shoot_flame_thrower_growth_v") Integer role_skill_shoot_flame_thrower_growth_v,
            @Param("role_skill_shoot_machine_gun_growth_v") Integer role_skill_shoot_machine_gun_growth_v,
            @Param("role_skill_shoot_heavy_weapon_growth_v") Integer role_skill_shoot_heavy_weapon_growth_v,
            @Param("role_skill_first_aid_growth_v") Integer role_skill_first_aid_growth_v,
            @Param("role_skill_history_growth_v") Integer role_skill_history_growth_v,
            @Param("role_skill_threaten_growth_v") Integer role_skill_threaten_growth_v,
            @Param("role_skill_jump_growth_v") Integer role_skill_jump_growth_v,
            @Param("role_skill_language_val1_growth_v") Integer role_skill_language_val1_growth_v,
            @Param("role_skill_language_val2_growth_v") Integer role_skill_language_val2_growth_v,
            @Param("role_skill_language_val3_growth_v") Integer role_skill_language_val3_growth_v,
            @Param("role_skill_mother_tongue_val_growth_v") Integer role_skill_mother_tongue_val_growth_v,
            @Param("role_skill_throw_growth_v") Integer role_skill_throw_growth_v,
            @Param("role_skill_track_growth_v") Integer role_skill_track_growth_v,
            @Param("role_skill_law_growth_v") Integer role_skill_law_growth_v,
            @Param("role_skill_library_use_growth_v") Integer role_skill_library_use_growth_v,
            @Param("role_skill_listen_growth_v") Integer role_skill_listen_growth_v,
            @Param("role_skill_locksmith_growth_v") Integer role_skill_locksmith_growth_v,
            @Param("role_skill_mechanical_repair_growth_v") Integer role_skill_mechanical_repair_growth_v,
            @Param("role_skill_medicine_growth_v") Integer role_skill_medicine_growth_v,
            @Param("role_skill_natural_world_growth_v") Integer role_skill_natural_world_growth_v,
            @Param("role_skill_navigate_growth_v") Integer role_skill_navigate_growth_v,
            @Param("role_skill_occult_growth_v") Integer role_skill_occult_growth_v,
            @Param("role_skill_operate_heavy_machinery_growth_v") Integer role_skill_operate_heavy_machinery_growth_v,
            @Param("role_skill_persuade_growth_v") Integer role_skill_persuade_growth_v,
            @Param("role_skill_drive_aircraft_growth_v") Integer role_skill_drive_aircraft_growth_v,
            @Param("role_skill_drive_ship_growth_v") Integer role_skill_drive_ship_growth_v,
            @Param("role_skill_psychoanalysis_growth_v") Integer role_skill_psychoanalysis_growth_v,
            @Param("role_skill_psychology_growth_v") Integer role_skill_psychology_growth_v,
            @Param("role_skill_ride_growth_v") Integer role_skill_ride_growth_v,
            @Param("role_skill_science_geology_growth_v") Integer role_skill_science_geology_growth_v,
            @Param("role_skill_science_chemistry_growth_v") Integer role_skill_science_chemistry_growth_v,
            @Param("role_skill_science_biology_growth_v") Integer role_skill_science_biology_growth_v,
            @Param("role_skill_science_math_growth_v") Integer role_skill_science_math_growth_v,
            @Param("role_skill_science_astronomy_growth_v") Integer role_skill_science_astronomy_growth_v,
            @Param("role_skill_science_physics_growth_v") Integer role_skill_science_physics_growth_v,
            @Param("role_skill_science_pharmacy_growth_v") Integer role_skill_science_pharmacy_growth_v,
            @Param("role_skill_science_botany_growth_v") Integer role_skill_science_botany_growth_v,
            @Param("role_skill_science_zoology_growth_v") Integer role_skill_science_zoology_growth_v,
            @Param("role_skill_science_cryptography_growth_v") Integer role_skill_science_cryptography_growth_v,
            @Param("role_skill_science_engineering_growth_v") Integer role_skill_science_engineering_growth_v,
            @Param("role_skill_science_meteorology_growth_v") Integer role_skill_science_meteorology_growth_v,
            @Param("role_skill_science_judicial_science_growth_v") Integer role_skill_science_judicial_science_growth_v,
            @Param("role_skill_sleight_of_hand_growth_v") Integer role_skill_sleight_of_hand_growth_v,
            @Param("role_skill_recon_growth_v") Integer role_skill_recon_growth_v,
            @Param("role_skill_stealth_growth_v") Integer role_skill_stealth_growth_v,
            @Param("role_skill_survival_growth_v") Integer role_skill_survival_growth_v,
            @Param("role_skill_swim_growth_v") Integer role_skill_swim_growth_v,
            @Param("role_skill_beast_training_growth_v") Integer role_skill_beast_training_growth_v,
            @Param("role_skill_diving_growth_v") Integer role_skill_diving_growth_v,
            @Param("role_skill_demolition_growth_v") Integer role_skill_demolition_growth_v,
            @Param("role_skill_read_lips_growth_v") Integer role_skill_read_lips_growth_v,
            @Param("role_skill_hypnosis_growth_v") Integer role_skill_hypnosis_growth_v,
            @Param("role_skill_artillery_growth_v") Integer role_skill_artillery_growth_v,
            @Param("role_skill_lore_val_growth_v") Integer role_skill_lore_val_growth_v,
            @Param("role_card_id_v") Integer role_card_id_v
    );
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = "UPDATE kesulu_online.role_skills SET role_skill_accounting_interst = :role_skill_accounting_interst_v, role_skill_anthropology_interst = :role_skill_anthropology_interst_v, role_skill_evaluation_interst = :role_skill_evaluation_interst_v, role_skill_archaeology_interst = :role_skill_archaeology_interst_v, role_skill_writing_interst = :role_skill_writing_interst_v, role_skill_music_theory_interst = :role_skill_music_theory_interst_v, role_skill_morris_dance_interst = :role_skill_morris_dance_interst_v, role_skill_opera_singing_interst = :role_skill_opera_singing_interst_v, role_skill_whitewasher_painter_interst = :role_skill_whitewasher_painter_interst_v, role_skill_photography_interst = :role_skill_photography_interst_v, role_skill_dance_interst = :role_skill_dance_interst_v, role_skill_art_interst = :role_skill_art_interst_v, role_skill_forge_interst = :role_skill_forge_interst_v, role_skill_pottery_making_interst = :role_skill_pottery_making_interst_v, role_skill_technical_drawing_interst = :role_skill_technical_drawing_interst_v, role_skill_farming_interst = :role_skill_farming_interst_v, role_skill_typing_interst = :role_skill_typing_interst_v, role_skill_shorthand_interst = :role_skill_shorthand_interst_v, role_skill_blown_glass_tube_interst = :role_skill_blown_glass_tube_interst_v, role_skill_tailor_interst = :role_skill_tailor_interst_v, role_skill_make_wine_interst = :role_skill_make_wine_interst_v, role_skill_fishing_interst = :role_skill_fishing_interst_v, role_skill_sculpture_interst = :role_skill_sculpture_interst_v, role_skill_acrobatics_interst = :role_skill_acrobatics_interst_v, role_skill_seduce_interst = :role_skill_seduce_interst_v, role_skill_climb_interst = :role_skill_climb_interst_v, role_skill_computer_interst = :role_skill_computer_interst_v, role_skill_credit_interst = :role_skill_credit_interst_v, role_skill_cthulhu_mythos_interst = :role_skill_cthulhu_mythos_interst_v, role_skill_disguise_interst = :role_skill_disguise_interst_v, role_skill_dodge_interst = :role_skill_dodge_interst_v, role_skill_car_driving_interst = :role_skill_car_driving_interst_v, role_skill_electrical_maintenance_interst = :role_skill_electrical_maintenance_interst_v, role_skill_electronics_interst = :role_skill_electronics_interst_v, role_skill_speech_skill_interst = :role_skill_speech_skill_interst_v, role_skill_combat_fight_interst = :role_skill_combat_fight_interst_v, role_skill_combat_whip_interst = :role_skill_combat_whip_interst_v, role_skill_combat_electric_saw_interst = :role_skill_combat_electric_saw_interst_v, role_skill_combat_axe_interst = :role_skill_combat_axe_interst_v, role_skill_combat_sword_interst = :role_skill_combat_sword_interst_v, role_skill_combat_hinge_interst = :role_skill_combat_hinge_interst_v, role_skill_combat_flail_interst = :role_skill_combat_flail_interst_v, role_skill_combat_spear_interst = :role_skill_combat_spear_interst_v, role_skill_shoot_pistol_interst = :role_skill_shoot_pistol_interst_v, role_skill_shoot_rifle_shotgun_interst = :role_skill_shoot_rifle_shotgun_interst_v, role_skill_shoot_archery_interst = :role_skill_shoot_archery_interst_v, role_skill_shoot_flame_thrower_interst = :role_skill_shoot_flame_thrower_interst_v, role_skill_shoot_machine_gun_interst = :role_skill_shoot_machine_gun_interst_v, role_skill_shoot_heavy_weapon_interst = :role_skill_shoot_heavy_weapon_interst_v, role_skill_first_aid_interst = :role_skill_first_aid_interst_v, role_skill_history_interst = :role_skill_history_interst_v, role_skill_threaten_interst = :role_skill_threaten_interst_v, role_skill_jump_interst = :role_skill_jump_interst_v, role_skill_language_val1_interst = :role_skill_language_val1_interst_v, role_skill_language_val2_interst = :role_skill_language_val2_interst_v, role_skill_language_val3_interst = :role_skill_language_val3_interst_v, role_skill_mother_tongue_val_interst = :role_skill_mother_tongue_val_interst_v, role_skill_throw_interst = :role_skill_throw_interst_v, role_skill_track_interst = :role_skill_track_interst_v, role_skill_law_interst = :role_skill_law_interst_v, role_skill_library_use_interst = :role_skill_library_use_interst_v, role_skill_listen_interst = :role_skill_listen_interst_v, role_skill_locksmith_interst = :role_skill_locksmith_interst_v, role_skill_mechanical_repair_interst = :role_skill_mechanical_repair_interst_v, role_skill_medicine_interst = :role_skill_medicine_interst_v, role_skill_natural_world_interst = :role_skill_natural_world_interst_v, role_skill_navigate_interst = :role_skill_navigate_interst_v, role_skill_occult_interst = :role_skill_occult_interst_v, role_skill_operate_heavy_machinery_interst = :role_skill_operate_heavy_machinery_interst_v, role_skill_persuade_interst = :role_skill_persuade_interst_v, role_skill_drive_aircraft_interst = :role_skill_drive_aircraft_interst_v, role_skill_drive_ship_interst = :role_skill_drive_ship_interst_v, role_skill_psychoanalysis_interst = :role_skill_psychoanalysis_interst_v, role_skill_psychology_interst = :role_skill_psychology_interst_v, role_skill_ride_interst = :role_skill_ride_interst_v, role_skill_science_geology_interst = :role_skill_science_geology_interst_v, role_skill_science_chemistry_interst = :role_skill_science_chemistry_interst_v, role_skill_science_biology_interst = :role_skill_science_biology_interst_v, role_skill_science_math_interst = :role_skill_science_math_interst_v, role_skill_science_astronomy_interst = :role_skill_science_astronomy_interst_v, role_skill_science_physics_interst = :role_skill_science_physics_interst_v, role_skill_science_pharmacy_interst = :role_skill_science_pharmacy_interst_v, role_skill_science_botany_interst = :role_skill_science_botany_interst_v, role_skill_science_zoology_interst = :role_skill_science_zoology_interst_v, role_skill_science_cryptography_interst = :role_skill_science_cryptography_interst_v, role_skill_science_engineering_interst = :role_skill_science_engineering_interst_v, role_skill_science_meteorology_interst = :role_skill_science_meteorology_interst_v, role_skill_science_judicial_science_interst = :role_skill_science_judicial_science_interst_v, role_skill_sleight_of_hand_interst = :role_skill_sleight_of_hand_interst_v, role_skill_recon_interst = :role_skill_recon_interst_v, role_skill_stealth_interst = :role_skill_stealth_interst_v, role_skill_survival_interst = :role_skill_survival_interst_v, role_skill_swim_interst = :role_skill_swim_interst_v, role_skill_beast_training_interst = :role_skill_beast_training_interst_v, role_skill_diving_interst = :role_skill_diving_interst_v, role_skill_demolition_interst = :role_skill_demolition_interst_v, role_skill_read_lips_interst = :role_skill_read_lips_interst_v, role_skill_hypnosis_interst = :role_skill_hypnosis_interst_v, role_skill_artillery_interst = :role_skill_artillery_interst_v, role_skill_lore_val_interst = :role_skill_lore_val_interst_v WHERE role_card_id = :role_card_id_v")
    void updateRoleSkillInterest(
            @Param("role_skill_accounting_interst_v") Integer role_skill_accounting_interst_v,
            @Param("role_skill_anthropology_interst_v") Integer role_skill_anthropology_interst_v,
            @Param("role_skill_evaluation_interst_v") Integer role_skill_evaluation_interst_v,
            @Param("role_skill_archaeology_interst_v") Integer role_skill_archaeology_interst_v,
            @Param("role_skill_writing_interst_v") Integer role_skill_writing_interst_v,
            @Param("role_skill_music_theory_interst_v") Integer role_skill_music_theory_interst_v,
            @Param("role_skill_morris_dance_interst_v") Integer role_skill_morris_dance_interst_v,
            @Param("role_skill_opera_singing_interst_v") Integer role_skill_opera_singing_interst_v,
            @Param("role_skill_whitewasher_painter_interst_v") Integer role_skill_whitewasher_painter_interst_v,
            @Param("role_skill_photography_interst_v") Integer role_skill_photography_interst_v,
            @Param("role_skill_dance_interst_v") Integer role_skill_dance_interst_v,
            @Param("role_skill_art_interst_v") Integer role_skill_art_interst_v,
            @Param("role_skill_forge_interst_v") Integer role_skill_forge_interst_v,
            @Param("role_skill_pottery_making_interst_v") Integer role_skill_pottery_making_interst_v,
            @Param("role_skill_technical_drawing_interst_v") Integer role_skill_technical_drawing_interst_v,
            @Param("role_skill_farming_interst_v") Integer role_skill_farming_interst_v,
            @Param("role_skill_typing_interst_v") Integer role_skill_typing_interst_v,
            @Param("role_skill_shorthand_interst_v") Integer role_skill_shorthand_interst_v,
            @Param("role_skill_blown_glass_tube_interst_v") Integer role_skill_blown_glass_tube_interst_v,
            @Param("role_skill_tailor_interst_v") Integer role_skill_tailor_interst_v,
            @Param("role_skill_make_wine_interst_v") Integer role_skill_make_wine_interst_v,
            @Param("role_skill_fishing_interst_v") Integer role_skill_fishing_interst_v,
            @Param("role_skill_sculpture_interst_v") Integer role_skill_sculpture_interst_v,
            @Param("role_skill_acrobatics_interst_v") Integer role_skill_acrobatics_interst_v,
            @Param("role_skill_seduce_interst_v") Integer role_skill_seduce_interst_v,
            @Param("role_skill_climb_interst_v") Integer role_skill_climb_interst_v,
            @Param("role_skill_computer_interst_v") Integer role_skill_computer_interst_v,
            @Param("role_skill_credit_interst_v") Integer role_skill_credit_interst_v,
            @Param("role_skill_cthulhu_mythos_interst_v") Integer role_skill_cthulhu_mythos_interst_v,
            @Param("role_skill_disguise_interst_v") Integer role_skill_disguise_interst_v,
            @Param("role_skill_dodge_interst_v") Integer role_skill_dodge_interst_v,
            @Param("role_skill_car_driving_interst_v") Integer role_skill_car_driving_interst_v,
            @Param("role_skill_electrical_maintenance_interst_v") Integer role_skill_electrical_maintenance_interst_v,
            @Param("role_skill_electronics_interst_v") Integer role_skill_electronics_interst_v,
            @Param("role_skill_speech_skill_interst_v") Integer role_skill_speech_skill_interst_v,
            @Param("role_skill_combat_fight_interst_v") Integer role_skill_combat_fight_interst_v,
            @Param("role_skill_combat_whip_interst_v") Integer role_skill_combat_whip_interst_v,
            @Param("role_skill_combat_electric_saw_interst_v") Integer role_skill_combat_electric_saw_interst_v,
            @Param("role_skill_combat_axe_interst_v") Integer role_skill_combat_axe_interst_v,
            @Param("role_skill_combat_sword_interst_v") Integer role_skill_combat_sword_interst_v,
            @Param("role_skill_combat_hinge_interst_v") Integer role_skill_combat_hinge_interst_v,
            @Param("role_skill_combat_flail_interst_v") Integer role_skill_combat_flail_interst_v,
            @Param("role_skill_combat_spear_interst_v") Integer role_skill_combat_spear_interst_v,
            @Param("role_skill_shoot_pistol_interst_v") Integer role_skill_shoot_pistol_interst_v,
            @Param("role_skill_shoot_rifle_shotgun_interst_v") Integer role_skill_shoot_rifle_shotgun_interst_v,
            @Param("role_skill_shoot_archery_interst_v") Integer role_skill_shoot_archery_interst_v,
            @Param("role_skill_shoot_flame_thrower_interst_v") Integer role_skill_shoot_flame_thrower_interst_v,
            @Param("role_skill_shoot_machine_gun_interst_v") Integer role_skill_shoot_machine_gun_interst_v,
            @Param("role_skill_shoot_heavy_weapon_interst_v") Integer role_skill_shoot_heavy_weapon_interst_v,
            @Param("role_skill_first_aid_interst_v") Integer role_skill_first_aid_interst_v,
            @Param("role_skill_history_interst_v") Integer role_skill_history_interst_v,
            @Param("role_skill_threaten_interst_v") Integer role_skill_threaten_interst_v,
            @Param("role_skill_jump_interst_v") Integer role_skill_jump_interst_v,
            @Param("role_skill_language_val1_interst_v") Integer role_skill_language_val1_interst_v,
            @Param("role_skill_language_val2_interst_v") Integer role_skill_language_val2_interst_v,
            @Param("role_skill_language_val3_interst_v") Integer role_skill_language_val3_interst_v,
            @Param("role_skill_mother_tongue_val_interst_v") Integer role_skill_mother_tongue_val_interst_v,
            @Param("role_skill_throw_interst_v") Integer role_skill_throw_interst_v,
            @Param("role_skill_track_interst_v") Integer role_skill_track_interst_v,
            @Param("role_skill_law_interst_v") Integer role_skill_law_interst_v,
            @Param("role_skill_library_use_interst_v") Integer role_skill_library_use_interst_v,
            @Param("role_skill_listen_interst_v") Integer role_skill_listen_interst_v,
            @Param("role_skill_locksmith_interst_v") Integer role_skill_locksmith_interst_v,
            @Param("role_skill_mechanical_repair_interst_v") Integer role_skill_mechanical_repair_interst_v,
            @Param("role_skill_medicine_interst_v") Integer role_skill_medicine_interst_v,
            @Param("role_skill_natural_world_interst_v") Integer role_skill_natural_world_interst_v,
            @Param("role_skill_navigate_interst_v") Integer role_skill_navigate_interst_v,
            @Param("role_skill_occult_interst_v") Integer role_skill_occult_interst_v,
            @Param("role_skill_operate_heavy_machinery_interst_v") Integer role_skill_operate_heavy_machinery_interst_v,
            @Param("role_skill_persuade_interst_v") Integer role_skill_persuade_interst_v,
            @Param("role_skill_drive_aircraft_interst_v") Integer role_skill_drive_aircraft_interst_v,
            @Param("role_skill_drive_ship_interst_v") Integer role_skill_drive_ship_interst_v,
            @Param("role_skill_psychoanalysis_interst_v") Integer role_skill_psychoanalysis_interst_v,
            @Param("role_skill_psychology_interst_v") Integer role_skill_psychology_interst_v,
            @Param("role_skill_ride_interst_v") Integer role_skill_ride_interst_v,
            @Param("role_skill_science_geology_interst_v") Integer role_skill_science_geology_interst_v,
            @Param("role_skill_science_chemistry_interst_v") Integer role_skill_science_chemistry_interst_v,
            @Param("role_skill_science_biology_interst_v") Integer role_skill_science_biology_interst_v,
            @Param("role_skill_science_math_interst_v") Integer role_skill_science_math_interst_v,
            @Param("role_skill_science_astronomy_interst_v") Integer role_skill_science_astronomy_interst_v,
            @Param("role_skill_science_physics_interst_v") Integer role_skill_science_physics_interst_v,
            @Param("role_skill_science_pharmacy_interst_v") Integer role_skill_science_pharmacy_interst_v,
            @Param("role_skill_science_botany_interst_v") Integer role_skill_science_botany_interst_v,
            @Param("role_skill_science_zoology_interst_v") Integer role_skill_science_zoology_interst_v,
            @Param("role_skill_science_cryptography_interst_v") Integer role_skill_science_cryptography_interst_v,
            @Param("role_skill_science_engineering_interst_v") Integer role_skill_science_engineering_interst_v,
            @Param("role_skill_science_meteorology_interst_v") Integer role_skill_science_meteorology_interst_v,
            @Param("role_skill_science_judicial_science_interst_v") Integer role_skill_science_judicial_science_interst_v,
            @Param("role_skill_sleight_of_hand_interst_v") Integer role_skill_sleight_of_hand_interst_v,
            @Param("role_skill_recon_interst_v") Integer role_skill_recon_interst_v,
            @Param("role_skill_stealth_interst_v") Integer role_skill_stealth_interst_v,
            @Param("role_skill_survival_interst_v") Integer role_skill_survival_interst_v,
            @Param("role_skill_swim_interst_v") Integer role_skill_swim_interst_v,
            @Param("role_skill_beast_training_interst_v") Integer role_skill_beast_training_interst_v,
            @Param("role_skill_diving_interst_v") Integer role_skill_diving_interst_v,
            @Param("role_skill_demolition_interst_v") Integer role_skill_demolition_interst_v,
            @Param("role_skill_read_lips_interst_v") Integer role_skill_read_lips_interst_v,
            @Param("role_skill_hypnosis_interst_v") Integer role_skill_hypnosis_interst_v,
            @Param("role_skill_artillery_interst_v") Integer role_skill_artillery_interst_v,
            @Param("role_skill_lore_val_interst_v") Integer role_skill_lore_val_interst_v,
            @Param("role_card_id_v") Integer role_card_id_v
    );
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = "UPDATE kesulu_online.role_skills SET role_skill_accounting_job = :role_skill_accounting_job_v, role_skill_anthropology_job = :role_skill_anthropology_job_v, role_skill_evaluation_job = :role_skill_evaluation_job_v, role_skill_archaeology_job = :role_skill_archaeology_job_v, role_skill_writing_job = :role_skill_writing_job_v, role_skill_music_theory_job = :role_skill_music_theory_job_v, role_skill_morris_dance_job = :role_skill_morris_dance_job_v, role_skill_opera_singing_job = :role_skill_opera_singing_job_v, role_skill_whitewasher_painter_job = :role_skill_whitewasher_painter_job_v, role_skill_photography_job = :role_skill_photography_job_v, role_skill_dance_job = :role_skill_dance_job_v, role_skill_art_job = :role_skill_art_job_v, role_skill_forge_job = :role_skill_forge_job_v, role_skill_pottery_making_job = :role_skill_pottery_making_job_v, role_skill_technical_drawing_job = :role_skill_technical_drawing_job_v, role_skill_farming_job = :role_skill_farming_job_v, role_skill_typing_job = :role_skill_typing_job_v, role_skill_shorthand_job = :role_skill_shorthand_job_v, role_skill_blown_glass_tube_job = :role_skill_blown_glass_tube_job_v, role_skill_tailor_job = :role_skill_tailor_job_v, role_skill_make_wine_job = :role_skill_make_wine_job_v, role_skill_fishing_job = :role_skill_fishing_job_v, role_skill_sculpture_job = :role_skill_sculpture_job_v, role_skill_acrobatics_job = :role_skill_acrobatics_job_v, role_skill_seduce_job = :role_skill_seduce_job_v, role_skill_climb_job = :role_skill_climb_job_v, role_skill_computer_job = :role_skill_computer_job_v, role_skill_credit_job = :role_skill_credit_job_v, role_skill_cthulhu_mythos_job = :role_skill_cthulhu_mythos_job_v, role_skill_disguise_job = :role_skill_disguise_job_v, role_skill_dodge_job = :role_skill_dodge_job_v, role_skill_car_driving_job = :role_skill_car_driving_job_v, role_skill_electrical_maintenance_job = :role_skill_electrical_maintenance_job_v, role_skill_electronics_job = :role_skill_electronics_job_v, role_skill_speech_skill_job = :role_skill_speech_skill_job_v, role_skill_combat_fight_job = :role_skill_combat_fight_job_v, role_skill_combat_whip_job = :role_skill_combat_whip_job_v, role_skill_combat_electric_saw_job = :role_skill_combat_electric_saw_job_v, role_skill_combat_axe_job = :role_skill_combat_axe_job_v, role_skill_combat_sword_job = :role_skill_combat_sword_job_v, role_skill_combat_hinge_job = :role_skill_combat_hinge_job_v, role_skill_combat_flail_job = :role_skill_combat_flail_job_v, role_skill_combat_spear_job = :role_skill_combat_spear_job_v, role_skill_shoot_pistol_job = :role_skill_shoot_pistol_job_v, role_skill_shoot_rifle_shotgun_job = :role_skill_shoot_rifle_shotgun_job_v, role_skill_shoot_archery_job = :role_skill_shoot_archery_job_v, role_skill_shoot_flame_thrower_job = :role_skill_shoot_flame_thrower_job_v, role_skill_shoot_machine_gun_job = :role_skill_shoot_machine_gun_job_v, role_skill_shoot_heavy_weapon_job = :role_skill_shoot_heavy_weapon_job_v, role_skill_first_aid_job = :role_skill_first_aid_job_v, role_skill_history_job = :role_skill_history_job_v, role_skill_threaten_job = :role_skill_threaten_job_v, role_skill_jump_job = :role_skill_jump_job_v, role_skill_language_val1_job = :role_skill_language_val1_job_v, role_skill_language_val2_job = :role_skill_language_val2_job_v, role_skill_language_val3_job = :role_skill_language_val3_job_v, role_skill_mother_tongue_val_job = :role_skill_mother_tongue_val_job_v, role_skill_throw_job = :role_skill_throw_job_v, role_skill_track_job = :role_skill_track_job_v, role_skill_law_job = :role_skill_law_job_v, role_skill_library_use_job = :role_skill_library_use_job_v, role_skill_listen_job = :role_skill_listen_job_v, role_skill_locksmith_job = :role_skill_locksmith_job_v, role_skill_mechanical_repair_job = :role_skill_mechanical_repair_job_v, role_skill_medicine_job = :role_skill_medicine_job_v, role_skill_natural_world_job = :role_skill_natural_world_job_v, role_skill_navigate_job = :role_skill_navigate_job_v, role_skill_occult_job = :role_skill_occult_job_v, role_skill_operate_heavy_machinery_job = :role_skill_operate_heavy_machinery_job_v, role_skill_persuade_job = :role_skill_persuade_job_v, role_skill_drive_aircraft_job = :role_skill_drive_aircraft_job_v, role_skill_drive_ship_job = :role_skill_drive_ship_job_v, role_skill_psychoanalysis_job = :role_skill_psychoanalysis_job_v, role_skill_psychology_job = :role_skill_psychology_job_v, role_skill_ride_job = :role_skill_ride_job_v, role_skill_science_geology_job = :role_skill_science_geology_job_v, role_skill_science_chemistry_job = :role_skill_science_chemistry_job_v, role_skill_science_biology_job = :role_skill_science_biology_job_v, role_skill_science_math_job = :role_skill_science_math_job_v, role_skill_science_astronomy_job = :role_skill_science_astronomy_job_v, role_skill_science_physics_job = :role_skill_science_physics_job_v, role_skill_science_pharmacy_job = :role_skill_science_pharmacy_job_v, role_skill_science_botany_job = :role_skill_science_botany_job_v, role_skill_science_zoology_job = :role_skill_science_zoology_job_v, role_skill_science_cryptography_job = :role_skill_science_cryptography_job_v, role_skill_science_engineering_job = :role_skill_science_engineering_job_v, role_skill_science_meteorology_job = :role_skill_science_meteorology_job_v, role_skill_science_judicial_science_job = :role_skill_science_judicial_science_job_v, role_skill_sleight_of_hand_job = :role_skill_sleight_of_hand_job_v, role_skill_recon_job = :role_skill_recon_job_v, role_skill_stealth_job = :role_skill_stealth_job_v, role_skill_survival_job = :role_skill_survival_job_v, role_skill_swim_job = :role_skill_swim_job_v, role_skill_beast_training_job = :role_skill_beast_training_job_v, role_skill_diving_job = :role_skill_diving_job_v, role_skill_demolition_job = :role_skill_demolition_job_v, role_skill_read_lips_job = :role_skill_read_lips_job_v, role_skill_hypnosis_job = :role_skill_hypnosis_job_v, role_skill_artillery_job = :role_skill_artillery_job_v, role_skill_lore_val_job = :role_skill_lore_val_job_v WHERE role_card_id = :role_card_id_v")
    void updateRoleSkillJob(
            @Param("role_skill_accounting_job_v") Integer role_skill_accounting_job_v,
            @Param("role_skill_anthropology_job_v") Integer role_skill_anthropology_job_v,
            @Param("role_skill_evaluation_job_v") Integer role_skill_evaluation_job_v,
            @Param("role_skill_archaeology_job_v") Integer role_skill_archaeology_job_v,
            @Param("role_skill_writing_job_v") Integer role_skill_writing_job_v,
            @Param("role_skill_music_theory_job_v") Integer role_skill_music_theory_job_v,
            @Param("role_skill_morris_dance_job_v") Integer role_skill_morris_dance_job_v,
            @Param("role_skill_opera_singing_job_v") Integer role_skill_opera_singing_job_v,
            @Param("role_skill_whitewasher_painter_job_v") Integer role_skill_whitewasher_painter_job_v,
            @Param("role_skill_photography_job_v") Integer role_skill_photography_job_v,
            @Param("role_skill_dance_job_v") Integer role_skill_dance_job_v,
            @Param("role_skill_art_job_v") Integer role_skill_art_job_v,
            @Param("role_skill_forge_job_v") Integer role_skill_forge_job_v,
            @Param("role_skill_pottery_making_job_v") Integer role_skill_pottery_making_job_v,
            @Param("role_skill_technical_drawing_job_v") Integer role_skill_technical_drawing_job_v,
            @Param("role_skill_farming_job_v") Integer role_skill_farming_job_v,
            @Param("role_skill_typing_job_v") Integer role_skill_typing_job_v,
            @Param("role_skill_shorthand_job_v") Integer role_skill_shorthand_job_v,
            @Param("role_skill_blown_glass_tube_job_v") Integer role_skill_blown_glass_tube_job_v,
            @Param("role_skill_tailor_job_v") Integer role_skill_tailor_job_v,
            @Param("role_skill_make_wine_job_v") Integer role_skill_make_wine_job_v,
            @Param("role_skill_fishing_job_v") Integer role_skill_fishing_job_v,
            @Param("role_skill_sculpture_job_v") Integer role_skill_sculpture_job_v,
            @Param("role_skill_acrobatics_job_v") Integer role_skill_acrobatics_job_v,
            @Param("role_skill_seduce_job_v") Integer role_skill_seduce_job_v,
            @Param("role_skill_climb_job_v") Integer role_skill_climb_job_v,
            @Param("role_skill_computer_job_v") Integer role_skill_computer_job_v,
            @Param("role_skill_credit_job_v") Integer role_skill_credit_job_v,
            @Param("role_skill_cthulhu_mythos_job_v") Integer role_skill_cthulhu_mythos_job_v,
            @Param("role_skill_disguise_job_v") Integer role_skill_disguise_job_v,
            @Param("role_skill_dodge_job_v") Integer role_skill_dodge_job_v,
            @Param("role_skill_car_driving_job_v") Integer role_skill_car_driving_job_v,
            @Param("role_skill_electrical_maintenance_job_v") Integer role_skill_electrical_maintenance_job_v,
            @Param("role_skill_electronics_job_v") Integer role_skill_electronics_job_v,
            @Param("role_skill_speech_skill_job_v") Integer role_skill_speech_skill_job_v,
            @Param("role_skill_combat_fight_job_v") Integer role_skill_combat_fight_job_v,
            @Param("role_skill_combat_whip_job_v") Integer role_skill_combat_whip_job_v,
            @Param("role_skill_combat_electric_saw_job_v") Integer role_skill_combat_electric_saw_job_v,
            @Param("role_skill_combat_axe_job_v") Integer role_skill_combat_axe_job_v,
            @Param("role_skill_combat_sword_job_v") Integer role_skill_combat_sword_job_v,
            @Param("role_skill_combat_hinge_job_v") Integer role_skill_combat_hinge_job_v,
            @Param("role_skill_combat_flail_job_v") Integer role_skill_combat_flail_job_v,
            @Param("role_skill_combat_spear_job_v") Integer role_skill_combat_spear_job_v,
            @Param("role_skill_shoot_pistol_job_v") Integer role_skill_shoot_pistol_job_v,
            @Param("role_skill_shoot_rifle_shotgun_job_v") Integer role_skill_shoot_rifle_shotgun_job_v,
            @Param("role_skill_shoot_archery_job_v") Integer role_skill_shoot_archery_job_v,
            @Param("role_skill_shoot_flame_thrower_job_v") Integer role_skill_shoot_flame_thrower_job_v,
            @Param("role_skill_shoot_machine_gun_job_v") Integer role_skill_shoot_machine_gun_job_v,
            @Param("role_skill_shoot_heavy_weapon_job_v") Integer role_skill_shoot_heavy_weapon_job_v,
            @Param("role_skill_first_aid_job_v") Integer role_skill_first_aid_job_v,
            @Param("role_skill_history_job_v") Integer role_skill_history_job_v,
            @Param("role_skill_threaten_job_v") Integer role_skill_threaten_job_v,
            @Param("role_skill_jump_job_v") Integer role_skill_jump_job_v,
            @Param("role_skill_language_val1_job_v") Integer role_skill_language_val1_job_v,
            @Param("role_skill_language_val2_job_v") Integer role_skill_language_val2_job_v,
            @Param("role_skill_language_val3_job_v") Integer role_skill_language_val3_job_v,
            @Param("role_skill_mother_tongue_val_job_v") Integer role_skill_mother_tongue_val_job_v,
            @Param("role_skill_throw_job_v") Integer role_skill_throw_job_v,
            @Param("role_skill_track_job_v") Integer role_skill_track_job_v,
            @Param("role_skill_law_job_v") Integer role_skill_law_job_v,
            @Param("role_skill_library_use_job_v") Integer role_skill_library_use_job_v,
            @Param("role_skill_listen_job_v") Integer role_skill_listen_job_v,
            @Param("role_skill_locksmith_job_v") Integer role_skill_locksmith_job_v,
            @Param("role_skill_mechanical_repair_job_v") Integer role_skill_mechanical_repair_job_v,
            @Param("role_skill_medicine_job_v") Integer role_skill_medicine_job_v,
            @Param("role_skill_natural_world_job_v") Integer role_skill_natural_world_job_v,
            @Param("role_skill_navigate_job_v") Integer role_skill_navigate_job_v,
            @Param("role_skill_occult_job_v") Integer role_skill_occult_job_v,
            @Param("role_skill_operate_heavy_machinery_job_v") Integer role_skill_operate_heavy_machinery_job_v,
            @Param("role_skill_persuade_job_v") Integer role_skill_persuade_job_v,
            @Param("role_skill_drive_aircraft_job_v") Integer role_skill_drive_aircraft_job_v,
            @Param("role_skill_drive_ship_job_v") Integer role_skill_drive_ship_job_v,
            @Param("role_skill_psychoanalysis_job_v") Integer role_skill_psychoanalysis_job_v,
            @Param("role_skill_psychology_job_v") Integer role_skill_psychology_job_v,
            @Param("role_skill_ride_job_v") Integer role_skill_ride_job_v,
            @Param("role_skill_science_geology_job_v") Integer role_skill_science_geology_job_v,
            @Param("role_skill_science_chemistry_job_v") Integer role_skill_science_chemistry_job_v,
            @Param("role_skill_science_biology_job_v") Integer role_skill_science_biology_job_v,
            @Param("role_skill_science_math_job_v") Integer role_skill_science_math_job_v,
            @Param("role_skill_science_astronomy_job_v") Integer role_skill_science_astronomy_job_v,
            @Param("role_skill_science_physics_job_v") Integer role_skill_science_physics_job_v,
            @Param("role_skill_science_pharmacy_job_v") Integer role_skill_science_pharmacy_job_v,
            @Param("role_skill_science_botany_job_v") Integer role_skill_science_botany_job_v,
            @Param("role_skill_science_zoology_job_v") Integer role_skill_science_zoology_job_v,
            @Param("role_skill_science_cryptography_job_v") Integer role_skill_science_cryptography_job_v,
            @Param("role_skill_science_engineering_job_v") Integer role_skill_science_engineering_job_v,
            @Param("role_skill_science_meteorology_job_v") Integer role_skill_science_meteorology_job_v,
            @Param("role_skill_science_judicial_science_job_v") Integer role_skill_science_judicial_science_job_v,
            @Param("role_skill_sleight_of_hand_job_v") Integer role_skill_sleight_of_hand_job_v,
            @Param("role_skill_recon_job_v") Integer role_skill_recon_job_v,
            @Param("role_skill_stealth_job_v") Integer role_skill_stealth_job_v,
            @Param("role_skill_survival_job_v") Integer role_skill_survival_job_v,
            @Param("role_skill_swim_job_v") Integer role_skill_swim_job_v,
            @Param("role_skill_beast_training_job_v") Integer role_skill_beast_training_job_v,
            @Param("role_skill_diving_job_v") Integer role_skill_diving_job_v,
            @Param("role_skill_demolition_job_v") Integer role_skill_demolition_job_v,
            @Param("role_skill_read_lips_job_v") Integer role_skill_read_lips_job_v,
            @Param("role_skill_hypnosis_job_v") Integer role_skill_hypnosis_job_v,
            @Param("role_skill_artillery_job_v") Integer role_skill_artillery_job_v,
            @Param("role_skill_lore_val_job_v") Integer role_skill_lore_val_job_v,
            @Param("role_card_id_v") Integer role_card_id_v
    );
    @Modifying
    @Transactional
    @Query(nativeQuery = true, value = "UPDATE kesulu_online.role_skills SET role_skill_language_type1 = :role_skill_language_type1_v, role_skill_language_type2 = :role_skill_language_type2_v, role_skill_language_type3 = :role_skill_language_type3_v, role_skill_mother_tongue_type = :role_skill_mother_tongue_type_v, role_skill_lore_type = :role_skill_lore_type_v WHERE role_card_id = :role_card_id_v")
    void updateRoleSkillOthers(
            @Param("role_skill_language_type1_v") String role_skill_language_type1_v,
            @Param("role_skill_language_type2_v") String role_skill_language_type2_v,
            @Param("role_skill_language_type3_v") String role_skill_language_type3_v,
            @Param("role_skill_mother_tongue_type_v") String role_skill_mother_tongue_type_v,
            @Param("role_skill_lore_type_v") String role_skill_lore_type_v,
            @Param("role_card_id_v") Integer role_card_id_v
    );
}

